INSERT
  INTO `gis_clientes`(`id`, `nombre`, `img`, `pais`, `tipo_cliente`)
  VALUES
    (1, 'Telefonica', 'telefonica-logo.png', 'peru', 'Telefonia'),
    (2, 'Bitel', 'bitel-logo.png', 'peru', 'Telefonia'),
    (3, 'Telefonica Empresas', 'telefonica-empresas-logo.png', 'peru', 'Telefonia'),
    (4, 'Americatel', 'americatel-logo.png', 'peru', 'Telefonia'),
    (5, 'Entel', 'entel-logo.png', 'peru', 'Telefonia'),
    (6, 'Claro', 'claro-logo.png', 'peru', 'Telefonia'),
    (7, 'Hidrandina', 'hidrandina-logo.png', 'peru', 'Energía'),
    (8, 'Distriluz', 'distriluz-logo.png', 'peru', 'Energía'),
    (9, 'Coga', 'coga-logo.png', 'peru', 'Energía'),
    (10, 'Electrosur', 'electrosur-logo.png', 'peru', 'Energía'),
    (11, 'Tgp', 'tgp-logo.png', 'peru', 'Energía'),
    (12, 'Enersur', 'enersur-logo.png', 'peru', 'Energía'),
    (13, 'Peru LNG', 'peru-lng-logo.png', 'peru', 'Energía'),
    (14, 'Statkraft', 'statkraft-logo.png', 'peru', 'Energía'),
    (15, 'Coes Sinac', 'coes-sinac-logo.png', 'peru', 'Energía'),
    (16, 'Poder Judicial', 'poder-judicial-logo.png', 'peru', 'Gobierno'),
    (17, 'Ministerio de Educación', 'ministerio-educacion-logo.png', 'peru', 'Gobierno'),
    (18, 'Fuerzas Armadas', 'fuerzas-armadas-logo.png', 'peru', 'Gobierno'),
    (19, 'ONPE', 'onpe-logo.png', 'peru', 'Gobierno'),
    (20, 'Ministerio del Ambiente', 'ministerio-ambiente-logo.png', 'peru', 'Gobierno'),
    (21, 'Sunarp', 'sunarp-logo.png', 'peru', 'Gobierno'),
    (22, 'RENIEC', 'reniec-logo.png', 'peru', 'Gobierno'),
    (23, 'Ministerio de Comercio Exterior y Turismo', 'ministerio-comercio-logo.png', 'peru', 'Gobierno'),
    (24, 'OSCE', 'osce-logo.png', 'peru', 'Gobierno'),
    (25, 'SENCICO', 'sencico-logo.png', 'peru', 'Gobierno'),
    (26, 'Marina de Guerra', 'marina-guerra-logo.png', 'peru', 'Gobierno'),
    (27, 'El Comercio', 'el-comercio-logo.png', 'peru', 'Industria'),
    (28, 'UNACEM', 'unacem-logo.png', 'peru', 'Industria'),
    (29, 'CIPSA', 'cipsa-logo.png', 'peru', 'Industria'),
    (30, 'SIDERPERU', 'siderperu-logo.png', 'peru', 'Industria'),
    (31, 'Banco de la Nación', 'banco-nacion-logo.png', 'peru', 'Finanzas'),
    (32, 'Grupo Sura', 'grupo-sura-logo.png', 'peru', 'Finanzas'),
    (33, 'La Positiva', 'la-positiva-logo.png', 'peru', 'Finanzas'),
    (34, 'Mibanco', 'mibanco-logo.png', 'peru', 'Finanzas'),
    (35, 'Diners Club', 'diners-club-logo.png', 'peru', 'Finanzas'),
    (36, 'Cavali', 'cavali-logo.png', 'peru', 'Finanzas'),
    (37, 'Tanner', 'tanner-logo.png', 'peru', 'Finanzas'),
    (38, 'Banco Financiero', 'banco-financiero-logo.png', 'peru', 'Finanzas'),
    (39, 'COFIDE', 'cofide-logo.png', 'peru', 'Finanzas'),
    (40, 'Gold Fields', 'gold-fields-logo.png', 'peru', 'Mineria'),
    (41, 'Myrstar', 'myrstar-logo.png', 'peru', 'Mineria'),
    (42, 'El Brocal', 'el-brocal-logo.png', 'peru', 'Mineria'),
    (43, 'Hochschild Minin', 'hochschild-minin-logo.png', 'peru', 'Mineria'),
    (44, 'Antamina', 'antamina-logo.png', 'peru', 'Mineria'),
    (45, 'APM Terminals', 'apm-terminals-logo.png', 'peru', 'Servicios'),
    (46, 'ITALTEL', 'italtel-logo.png', 'peru', 'Servicios'),
    (47, 'GMD', 'gmd-logo.png', 'peru', 'Servicios'),
    (48, 'NEPTUNIA', 'neptunia-logo.png', 'peru', 'Servicios'),
    (49, 'Centria', 'centria-logo.png', 'peru', 'Servicios'),
    (50, 'Montana', 'montana-logo.png', 'peru', 'Servicios'),
    (51, 'CIP', 'cip-logo.png', 'peru', 'Servicios'),
    (52, 'Overall', 'overall-logo.png', 'peru', 'Servicios'),
    (53, 'UNICON', 'unicon-logo.png', 'peru', 'Servicios'),
    (54, 'LINEA', 'linea-logo.png', 'peru', 'Servicios'),
    (55, 'Tata Consultancy Services', 'tata-consultancy-services-logo.png', 'peru', 'Servicios'),
    (56, 'SUMTEC', 'sumtec-logo.png', 'peru', 'Servicios'),
    (57, 'HERMES', 'hermes-logo.png', 'peru', 'Servicios'),
    (58, 'Markham College', 'markham-college-logo.png', 'peru', 'Salud y Eduación'),
    (59, 'Auna', 'auna-logo.png', 'peru', 'Salud y Eduación'),
    (60, 'IFB', 'ifb-logo.png', 'peru', 'Salud y Eduación'),
    (61, 'UP', 'universidad-pacifico-logo.png', 'peru', 'Salud y Eduación'),
    (62, 'UPAO', 'upao-logo.png', 'peru', 'Salud y Eduación'),
    (63, 'INICTEL-UNI', 'inictel-uni-logo.png', 'peru', 'Salud y Eduación');
